### ISSUE TITLE
Return default value on error

### ISSUE THREAD

**Issue by arobsco** [B3n3/Adobe-Launch-Mapping-Table#1]
At the moment the mapping table extension fails and throws a console error (_Failed to execute data element module mapping-table/src/lib/dataElements/mappingTable.js for data element xxx. Cannot read property 'toLowerCase' of undefined_) if the input data element is undefined.

Can the extension be updated to allow returning of the default value in the event that the input is undefined?

**Comment by B3n3** [comment]
Hi Andrew, thanks for pointing out this behavior.
Indeed, it is not desirable that the data element fails and consequently stops the execution of the respective rule/action. 

Making a change requires to be backwards compatible though.
In case the input is `undefined `and the mapping table data element fails, what would you expect as output?
Simply `undefined`?
I think this is the only default on-error behavior which is acceptable.

Cheers, Ben

**Comment by arobsco** [comment]
For me personally (and this may well be one that needs discussed on Slack or something) if the option to return the input is enabled then return undefined, if its not return the data elements default value. If that's not possible or there is something I'm missing then I'd be fine with undefined returned rather than failing completely.

**Comment by B3n3** [comment]
I think this is fine as by now, there is no return value at all, in case of an error.
If the "return the input" option is enabled I'm happy to return whatever the input was, even if an error occurs.
I believe this would then either be `null` or `undefined`, because every valid string should not throw an error.

I'm going to address this behavior in the next release. Thanks for pointing it out Andrew :)
